
export const FETCH_INITIAL_FORCAST = 'FETCH_INITIAL_FORCAST'
export const GET_LOCATION = 'GET_LOCATION'
export const WEATHER_HAS_ERRORED = 'WEATHER_HAS_ERRORED'
export const WEATHER_IS_LOADING = 'WEATHER_IS_LOADING'
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'
export const SEARCH_LOCATION = "SEARCH_LOCATION"
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS'
export const LOCATION_HAS_ERRORED = 'LOCATION_HAS_ERRORED'
export const LOCATION_IS_LOADING = 'LOCATION_IS_LOADING'
